app/app/models/users.py
from flask_login import UserMixin
from app import db
import qrcode
from io import BytesIO
import base64
from PIL import Image
import os
from flask import url_for, current_app

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    idUser = db.Column(db.Integer, primary_key=True)
    nameUser = db.Column(db.String(80), unique=True, nullable=False)
    passwordUser = db.Column(db.String(120), nullable=False)
    
    loansUser = db.relationship("Loan", back_populates="user", lazy='dynamic')
    computerLoansUser = db.relationship('ComputerLoan', back_populates='user', lazy='dynamic')

    def get_id(self):
        return str(self.idUser)

    def to_dict(self):
        return {
            "idUser": self.idUser,
            "nameUser": self.nameUser
        }

    def generate_qr(self):
        # Datos del usuario para el QR
        import json
        from PIL import Image
        user_data = json.dumps({
            'ID': self.idUser,
            'Name': self.nameUser
        })
        print("Generando código QR para el usuario:", user_data)
        # Generar el código QR
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=10,
            border=4,
        )
        qr.add_data(user_data)
        qr.make(fit=True)
        
        # Crear una imagen del QR
        img_qr = qr.make_image(fill='black', back_color='white').convert('RGB')
        
        # Cargar la imagen que se incluirá en el QR
        logo_path = os.path.join(current_app.root_path, 'static', 'img', 'sena.png')
        logo = Image.open(logo_path)
                
        # Calcular el tamaño del logo
        logo_size = 50
        logo = logo.resize((logo_size, logo_size))
        
        # Calcular la posición para centrar el logo en el QR
        pos = ((img_qr.size[0] - logo_size) // 2, (img_qr.size[1] - logo_size) // 2)
        
        # Pegar el logo en el QR
        img_qr.paste(logo, pos)
        
        # Convertir la imagen a base64
        buffered = BytesIO()
        img_qr.save(buffered, format="PNG")
        img_str = base64.b64encode(buffered.getvalue()).decode()
        
        return img_str

app/app/routes/users_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, send_file
from app.models.users import User
from app import db
from io import BytesIO
import base64
import json

bp = Blueprint('user', __name__, url_prefix='/User')

@bp.route('/')
def index():
    data = User.query.all()
    return render_template('users/index.html', data=data)

@bp.route('/js')
def indexjs():
    data = User.query.all()
        # Serializar los datos usando una comprensión de lista
    result = [user.to_dict() for user in data]  # Asegúrate de que el modelo User tenga un método to_dict()
    
    # Devolver la respuesta JSON
    return jsonify(result)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nameUser = request.form['nameUser']
        passwordUser = request.form['passwordUser']        
        new_user = User(nameUser=nameUser, passwordUser=passwordUser)
        db.session.add(new_user)
        db.session.commit()
        
        return redirect(url_for('user.index'))
    return render_template('users/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        user.nameUser = request.form['nameUser']
        user.passwordUser = request.form['passwordUser']
        db.session.commit()        
        return redirect(url_for('user.index'))

    return render_template('users/edit.html', user=user)
@bp.route('/detail/<int:id>')
def detail(id):
    user = User.query.get_or_404(id)
    return render_template('users/detail.html', user=user)

@bp.route('/delete/<int:id>')
def delete(id):
    user = User.query.get_or_404(id)    
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user.index'))

@bp.route('/qr/<int:id>')
def generate_qr(id):
    print("Entrando a la ruta de generación de QR para el usuario con ID:", id)
    user = User.query.get_or_404(id)
    qr_code_base64 = user.generate_qr()
    # Decodificar la imagen del QR desde base64
    qr_code_img = base64.b64decode(qr_code_base64)
    return send_file(BytesIO(qr_code_img), mimetype='image/png')


@bp.route('/read_qr', methods=['POST'])
def read_qr():
    from pyzbar.pyzbar import decode
    from PIL import Image
    import json

    if 'qr_image' not in request.files:
        return "No se ha proporcionado una imagen de QR", 400

    qr_image = request.files['qr_image']
    img = Image.open(qr_image)
    decoded_objects = decode(img)

    if not decoded_objects:
        return "No se pudo leer el código QR", 400

    qr_data = decoded_objects[0].data.decode('utf-8')
    user_data = json.loads(qr_data)
    user_id = user_data.get('ID')

    if not user_id:
        return "El código QR no contiene un ID de usuario válido", 400

    user = User.query.get(user_id)
    if not user:
        return "Usuario no encontrado", 404

    return render_template('users/detail.html', user=user)

app/app/templates/users/add.html
{% extends "base.html" %}
{% block titulo_pagina %}Agregar Usuario{% endblock %}
{% block content %}
<form action="{{ url_for('user.add') }}" method="post" class="needs-validation" novalidate>
    <div class="form-group mb-3">
        <label for="nameUser" class="form-label">Nombre:</label>
        <input type="text" id="nameUser" name="nameUser" required class="form-control">
        <div class="invalid-feedback">
            Por favor, ingrese un nombre de usuario.
        </div>
    </div>
    
    <div class="form-group mb-3">
        <label for="passwordUser" class="form-label">Contraseña:</label>
        <input type="password" id="passwordUser" name="passwordUser" required class="form-control">
        <div class="invalid-feedback">
            Por favor, ingrese una contraseña.
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary">Agregar Usuario</button>
</form>

{% endblock %}

app/app/templates/users/detail.html
{% extends "base.html" %}
{% block titulo_pagina %}Usuario {{ user.nameUser }}{% endblock %}
{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <td>{{ user.idUser }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ user.nameUser }}</td>
            </tr>
            <tr>
                <th>Contraseña</th>
                <td>{{ user.passwordUser }}</td>
            </tr>
        </table>
        <div class="d-flex justify-content-between">
            <a href="{{ url_for('user.edit', id=user.idUser) }}" class="btn btn-primary btn-sm mb-1">
                <i class="bi bi-pencil-square"></i>
            </a>
            <a href="{{ url_for('user.delete', id=user.idUser) }}" class="btn btn-danger btn-sm mb-1">
                <i class="bi bi-trash"></i>
            </a>
        </div>
        <h2 class="text-center">Código QR</h2>
        <div class="text-center">
            <img src="{{ url_for('user.generate_qr', id=user.idUser) }}" alt="QR Code" class="img-fluid">
        </div>
    </div>
{% endblock %}

app/app/templates/users/edit.html
{% extends "base.html" %}
{% block titulo_pagina %}Editar Usuario {{ user.nameUser }}{% endblock %}
{% block content %}
<h1>Editar Usuario</h1>
<form action="{{ url_for('user.edit', id=user.idUser) }}" method="post">
    <div class="form-group mb-3">
        <label for="nameUser" class="form-label">Nombre:</label>
        <input type="text" id="nameUser" name="nameUser" value="{{ user.nameUser }}" required class="form-control">
    </div>
   
    <div class="form-group mb-3">
        <label for="passwordUser" class="form-label">Contraseña:</label>
        <input type="password" id="passwordUser" name="passwordUser" value="{{ user.passwordUser }}" required class="form-control">
    </div>
    
    <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
</form>

{% endblock %}

app/app/templates/users/index.html
{% extends "base.html" %}
{% block titulo_pagina %}Lista de Usuarios{% endblock %}
{% block content %}
    
    <div class="text-start">
        <a href="{{ url_for('user.add') }}" class="btn btn-primary btn-sm mb-1">
            <i class="bi bi-person-plus"></i> Agregar usuario
        </a>

        <!-- Botón para abrir el lector de QR -->
        <a href="#" class="btn btn-sm btn-success mb-1" data-bs-toggle="modal" data-bs-target="#qrReaderModal">
            <i class="bi bi-qr-code-scan"></i> Usar Lector de QR
        </a>
    </div>
    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Buscar usuario.">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Contraseña</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody id="userTable">
            {% for user in data %}
                <tr>
                    <td>{{ user.idUser }}</td>
                    <td>{{ user.nameUser }}</td>
                    <td>{{ user.passwordUser }}</td>
                    <td>
                        <a href="{{ url_for('user.detail', id=user.idUser) }}" class="btn btn-success btn-sm mb-1">
                            <i class="bi bi-person"></i>
                        </a>
                        <a href="{{ url_for('user.edit', id=user.idUser) }}" class="btn btn-primary btn-sm mb-1">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <a href="{{ url_for('user.delete', id=user.idUser) }}" class="btn btn-danger btn-sm mb-1">
                            <i class="bi bi-trash"></i>
                        </a>
                        <button type="button" class="btn btn-info btn-sm mb-1" data-bs-toggle="modal" data-bs-target="#qrModal{{ user.idUser }}">
                            <i class="bi bi-qr-code"></i>
                        </button>
                      
                        <!-- Modal -->
                        <div class="modal fade" id="qrModal{{ user.idUser }}" tabindex="-1" aria-labelledby="qrModalLabel{{ user.idUser }}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="qrModalLabel{{ user.idUser }}">Código QR para {{ user.nameUser }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <img src="{{ url_for('user.generate_qr', id=user.idUser) }}" alt="QR Code" class="img-fluid">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary btn-sm w-100 mb-1" data-bs-dismiss="modal">Cerrar</button>
                                        <a href="{{ url_for('user.generate_qr', id=user.idUser) }}" class="btn btn-primary btn-sm w-100 mb-1" download="qr_{{ user.nameUser }}.png">Guardar imagen</a>
                                      </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        document.getElementById('searchInput').addEventListener('keyup', function() {
            const searchValue = this.value.toLowerCase();
            const rows = document.querySelectorAll('#userTable tr');
            rows.forEach(row => {
                const userName = row.querySelector('td:nth-child(2)').textContent.toLowerCase();
                if (userName.includes(searchValue)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    </script>
 

    <!-- Modal para lector de QR -->
    <div class="modal fade" id="qrReaderModal" tabindex="-1" aria-labelledby="qrReaderModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="qrReaderModalLabel">Lector de Código QR</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Contenedor para el lector de QR -->
                    <div id="reader" style="width: 100%;"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        let html5QrcodeScanner;

        function onScanSuccess(decodedText, decodedResult) {
            try {
                const jsonObject = JSON.parse(decodedText);                
                // Accede a cada propiedad del objeto JSON
                const id = jsonObject.ID;
                const name = jsonObject.Name;
                window.location.href = `/User/detail/${id}`;
            } catch (error) {
                // Si el texto decodificado no es un JSON válido, muestra un error
                console.error("Error al parsear el QR a JSON:", error);
                alert(`Código QR escaneado: ${decodedText}\nNota: El texto no es un JSON válido.`);
            }
        }


        function onScanFailure(error) {
            console.warn(`Error de escaneo: ${error}`);
        }

        const qrReaderModal = document.getElementById('qrReaderModal');

        qrReaderModal.addEventListener('shown.bs.modal', function () {
            html5QrcodeScanner = new Html5QrcodeScanner("reader", { fps: 10, qrbox: 250 });
            html5QrcodeScanner.render(onScanSuccess, onScanFailure);
        });

        qrReaderModal.addEventListener('hidden.bs.modal', function () {
            if (html5QrcodeScanner) {
                html5QrcodeScanner.clear().then(() => {
                    console.log("Lector de QR detenido y limpiado.");
                }).catch((error) => {
                    console.error("Error al detener el lector de QR: ", error);
                });
            }
        });
    </script>

        <!-- Bootstrap y script de HTML5-Qrcode -->
        <script src="{{ url_for('static', filename='html5-qrcode.min.js') }}"></script>
  </div>
{% endblock %}