app/app/models/authors.py
from app import db
class Author(db.Model):
    __tablename__ = 'authors'
    idAuthor = db.Column(db.Integer, primary_key=True)
    nameAuthor = db.Column(db.String(255), nullable=False)
    nationalityAuthor = db.Column(db.String(255), nullable=False)
    
    books = db.relationship("Book", back_populates="author", lazy='dynamic')
    
    def __repr__(self):
        return f'<Author {self.nameAuthor}>'
   

app/app/routes/author_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.authors import Author
from app import db

bp = Blueprint('author', __name__, url_prefix='/Author')

@bp.route('/')
def index():
    authors = Author.query.all()   
    return render_template('authors/index.html', data=authors)

@bp.route('/list/<int:id>', methods=['GET', 'POST'])
def list(id):
    author = Author.query.get_or_404(id)
    books = author.books
    return render_template('authors/list.html', books=books)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nameAuthor = request.form['nameAuthor']
        nationalityAuthor = request.form['nationalityAuthor']
        new_author = Author(nameAuthor=nameAuthor, nationalityAuthor=nationalityAuthor)
        db.session.add(new_author)
        db.session.commit()
        
        return redirect(url_for('author.index'))

    return render_template('authors/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    author = Author.query.get_or_404(id)

    if request.method == 'POST':
        author.nameAuthor = request.form['nameAuthor']
        author.nationalityAuthor = request.form['nationalityAuthor']
        db.session.commit()
        return redirect(url_for('author.index'))

    return render_template('authors/edit.html', author=author)
    

@bp.route('/delete/<int:id>')
def delete(id):
    author = Author.query.get_or_404(id)
    db.session.delete(author)
    db.session.commit()

    return redirect(url_for('author.index'))

app/app/routes/book_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.books import Book
from app.models.authors import Author
from app import db

bp = Blueprint('book', __name__, url_prefix='/Book')

@bp.route('/')
def index():
    data = Book.query.all()
    return render_template('books/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        titleBook = request.form['titleBook']
        authorId = request.form['authorId']
        
        new_book = Book(titleBook=titleBook, authorId=authorId)
        db.session.add(new_book)
        db.session.commit()
        
        return redirect(url_for('book.index'))
    
    data = Author.query.all()
    return render_template('books/add.html', data=data)

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    book = Book.query.get_or_404(id)

    if request.method == 'POST':
        book.titleBook = request.form['titleBook']
        book.authorId = request.form['authorId']
        db.session.commit()        
        return redirect(url_for('book.index'))

    authors = Author.query.all()
    return render_template('books/edit.html', book=book, authors=authors)

@bp.route('/delete/<int:id>')
def delete(id):
    book = Book.query.get_or_404(id)    
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for('book.index'))

app/app/templates/authors/List.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista de Libros</h1>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Autor</th>
            <th>Acciones</th>
        </tr>
        {% for book in books %}
            <tr>
                <td>{{ book.idBook }}</td>
                <td>{{ book.titleBook }}</td>
                <td>{{ book.author.nameAuthor }}</td>
                <td>
                    <a href="{{ url_for('book.edit', id=book.idBook) }}">Editar</a>
                    <a href="{{ url_for('book.delete', id=book.idBook) }}">Eliminar</a>                 
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('book.add') }}">Agregar Libro</a>
    <br>
    <a href="{{ url_for('author.index') }}">Ir a Autor</a> 

{% endblock %}

app/app/templates/authors/add.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-4 mb-4">Agregar Autor</h1>
    <form action="{{ url_for('author.add') }}" method="post" class="form-group p-4 border rounded shadow-sm">
        <div class="mb-3">
            <label for="nameAuthor" class="form-label">Nombre:</label>
            <input type="text" id="nameAuthor" name="nameAuthor" class="form-control rounded-pill" required>
        </div>

        <div class="mb-3">
            <label for="nationalityAuthor" class="form-label">Nacionalidad:</label>
            <input type="text" id="nationalityAuthor" name="nationalityAuthor" class="form-control rounded-pill" required>
        </div>
        
        <button type="submit" class="btn btn-primary rounded-pill">Agregar Autor</button>
    </form>
{% endblock %}

app/app/templates/authors/edit.html
{% extends "base.html" %}

{% block content %}
    <h1>Editar Autor</h1>
    <form action="{{ url_for('author.edit', id=author.idAuthor) }}" method="post" class="form-group">
        <label for="nameAuthor">Nombre:</label>
        <input type="text" id="nameAuthor" name="nameAuthor" value="{{ author.nameAuthor }}" required class="form-control">
        
        <label for="nationalityAuthor">Nacionalidad:</label>
        <input type="text" id="nationalityAuthor" name="nationalityAuthor" value="{{ author.nationalityAuthor }}" required class="form-control">
        
        <button type="submit" class="btn btn-primary">Actualizar Autor</button>
    </form>
{% endblock %}

app/app/templates/authors/index.html
{% extends "base.html" %}

{% block content %}
<h1>Lista de Autores</h1>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Nacionalidad</th>
            <th>Acciones</th>
        </tr>
        {% for author in data %}
            <tr>
                <td>{{ author.idAuthor }}</td>
                <td>{{ author.nameAuthor }}</td>
                <td>{{ author.nationalityAuthor }}</td>
                <td>
                    <a href="{{ url_for('author.edit', id=author.idAuthor) }}">Editar</a>
                    <a href="{{ url_for('author.list', id=author.idAuthor) }}">Listar Libros del Autor</a>
                    <a href="{{ url_for('author.delete', id=author.idAuthor) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('author.add') }}">Agregar Autor</a>
    <br>
    <a href="{{ url_for('book.index') }}">Ir a Libro</a>
{% endblock %}