app/app/routes/book_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.books import Book
from app.models.authors import Author
from app import db

bp = Blueprint('book', __name__, url_prefix='/Book')

@bp.route('/')
def index():
    data = Book.query.all()
    return render_template('books/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        titleBook = request.form['titleBook']
        authorId = request.form['authorId']
        
        new_book = Book(titleBook=titleBook, authorId=authorId)
        db.session.add(new_book)
        db.session.commit()
        
        return redirect(url_for('book.index'))
    
    data = Author.query.all()
    return render_template('books/add.html', data=data)

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    book = Book.query.get_or_404(id)

    if request.method == 'POST':
        book.titleBook = request.form['titleBook']
        book.authorId = request.form['authorId']
        db.session.commit()        
        return redirect(url_for('book.index'))

    authors = Author.query.all()
    return render_template('books/edit.html', book=book, authors=authors)

@bp.route('/delete/<int:id>')
def delete(id):
    book = Book.query.get_or_404(id)    
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for('book.index'))

app/app/routes/loans_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models.loans import Loan
from app.models.books import Book
from app.models.users import User
from app import db
from datetime import datetime, timedelta

bp = Blueprint('loan', __name__, url_prefix='/Loan')

@bp.route('/')
def index():
    loans = Loan.query.all()
    return render_template('loans/index.html', loans=loans)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        bookId = request.form['bookId']
        userId = request.form['userId']
        returnDate = datetime.now() + timedelta(days=14)  # Préstamo por 14 días
        
        new_loan = Loan(bookId=bookId, userId=userId, returnDate=returnDate)
        db.session.add(new_loan)
        db.session.commit()
        
        return redirect(url_for('loan.index'))
    
    books = Book.query.all()
    users = User.query.all()
    return render_template('loans/add.html', books=books, users=users)

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    loan = Loan.query.get_or_404(id)
    
    if request.method == 'POST':
        loan.returnDate = datetime.strptime(request.form['returnDate'], '%Y-%m-%d')
        loan.fine = float(request.form['fine'])
        loan.status = request.form['status']
        db.session.commit()
        return redirect(url_for('loan.index'))
    
    return render_template('loans/edit.html', loan=loan)

@bp.route('/delete/<int:id>')
def delete(id):
    loan = Loan.query.get_or_404(id)
    db.session.delete(loan)
    db.session.commit()
    return redirect(url_for('loan.index'))

@bp.route('/return/<int:id>')
def return_book(id):
    loan = Loan.query.get_or_404(id)
    loan.status = 'Returned'
    
    if datetime.now() > loan.returnDate:
        days_late = (datetime.now() - loan.returnDate).days
        loan.fine = days_late * 1.0  # Multa de 1.0 por día de retraso
    
    db.session.commit()
    return redirect(url_for('loan.index'))

app/app/routes/room_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.rooms import Room
from app import db

bp = Blueprint('room', __name__, url_prefix='/room')

@bp.route('/')
def index():
    data = Room.query.all()
    return render_template('rooms/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        new_room = Room(name=name, description=description)
        db.session.add(new_room)
        db.session.commit()
        
        return redirect(url_for('room.index'))
    return render_template('rooms/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    room = Room.query.get_or_404(id)
    if request.method == 'POST':
        room.name = request.form['name']
        room.description = request.form['description']
        db.session.commit()
        return redirect(url_for('room.index'))

    return render_template('rooms/edit.html', room=room)

@bp.route('/delete/<int:id>')
def delete(id):
    room = Room.query.get_or_404(id)
    db.session.delete(room)
    db.session.commit()
    return redirect(url_for('room.index'))

app/app/routes/users_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, send_file
from app.models.users import User
from app import db
from io import BytesIO
import base64
import json

bp = Blueprint('user', __name__, url_prefix='/User')

@bp.route('/')
def index():
    data = User.query.all()
    return render_template('users/index.html', data=data)

@bp.route('/js')
def indexjs():
    data = User.query.all()
        # Serializar los datos usando una comprensión de lista
    result = [user.to_dict() for user in data]  # Asegúrate de que el modelo User tenga un método to_dict()
    
    # Devolver la respuesta JSON
    return jsonify(result)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nameUser = request.form['nameUser']
        passwordUser = request.form['passwordUser']        
        new_user = User(nameUser=nameUser, passwordUser=passwordUser)
        db.session.add(new_user)
        db.session.commit()
        
        return redirect(url_for('user.index'))
    return render_template('users/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        user.nameUser = request.form['nameUser']
        user.passwordUser = request.form['passwordUser']
        db.session.commit()        
        return redirect(url_for('user.index'))

    return render_template('users/edit.html', user=user)
@bp.route('/detail/<int:id>')
def detail(id):
    user = User.query.get_or_404(id)
    return render_template('users/detail.html', user=user)

@bp.route('/delete/<int:id>')
def delete(id):
    user = User.query.get_or_404(id)    
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user.index'))

@bp.route('/qr/<int:id>')
def generate_qr(id):
    print("Entrando a la ruta de generación de QR para el usuario con ID:", id)
    user = User.query.get_or_404(id)
    qr_code_base64 = user.generate_qr()
    # Decodificar la imagen del QR desde base64
    qr_code_img = base64.b64decode(qr_code_base64)
    return send_file(BytesIO(qr_code_img), mimetype='image/png')


@bp.route('/read_qr', methods=['POST'])
def read_qr():
    from pyzbar.pyzbar import decode
    from PIL import Image
    import json

    if 'qr_image' not in request.files:
        return "No se ha proporcionado una imagen de QR", 400

    qr_image = request.files['qr_image']
    img = Image.open(qr_image)
    decoded_objects = decode(img)

    if not decoded_objects:
        return "No se pudo leer el código QR", 400

    qr_data = decoded_objects[0].data.decode('utf-8')
    user_data = json.loads(qr_data)
    user_id = user_data.get('ID')

    if not user_id:
        return "El código QR no contiene un ID de usuario válido", 400

    user = User.query.get(user_id)
    if not user:
        return "Usuario no encontrado", 404

    return render_template('users/detail.html', user=user)

app/app/templates/base.html
<!DOCTYPE html>
<html lang="es" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Aplicación</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='all.min.css') }}">
</head>
<body class="d-flex flex-column h-100 bg-light">
  {% include 'menu.html' %}
  <main class="flex-shrink-0">
    <div class="container mt-4 mx-auto">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}             
          {% for category, message in messages %}
            <div class="flash-message alert alert-{{ category }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <div class="row justify-content-center">
        <div class="col-md-10">
          <div class="card shadow-sm border border-2 border-primary">
            <div class="card-header bg-primary text-white">
              <h4 class="mb-0 text-center">{% block titulo_pagina %}{% endblock %}</h4>
            </div>
            <div class="card-body">
              <div class="container-fluid p-3">
                {% block content %}
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  <footer class="footer mt-auto py-3 bg-dark text-white">
    <div class="container text-center">
      <span class="text-white">&copy; 2024 Mi Aplicación. Esta obra está bajo una <a href="http://creativecommons.org/licenses/by/4.0/" class="text-white">Licencia Creative Commons Atribución 4.0 Internacional</a>.</span>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/app/templates/login.html
{% extends "base.html" %}
{% block titulo_pagina %}Bienvenido a mi aplicativo{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg border-0 rounded-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h1 class="h4">Iniciar sesión</h1>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ url_for('auth.login') }}">
                            <div class="form-group mb-3">
                                <label for="nameUser" class="form-label">Usuario</label>
                                <input type="text" name="nameUser" id="nameUser" class="form-control" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="passwordUser" class="form-label">Contraseña</label>
                                <input type="password" name="passwordUser" id="passwordUser" class="form-control" required>
                            </div>
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary btn-block">
                                    <i class="bi bi-box-arrow-in-right"></i> Iniciar Sesión
                                </button>
                                <a href="{{ url_for('user.add') }}" class="btn btn-secondary btn-block">
                                    <i class="bi bi-person-plus"></i> Crear Cuenta
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/app/templates/menu.html
    <!-- Menú de Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
          <a class="navbar-brand" href="/">Biblioteca</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" 
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                  <!-- Usuarios -->
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarUsuarios" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Usuarios
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarUsuarios">
                          <li><a class="dropdown-item" href="{{ url_for('user.index') }}">Listado</a></li>
                          <li><a class="dropdown-item" href="{{ url_for('user.add') }}">Agregar</a></li>
                      </ul>
                  </li>
                  <!-- Autores -->
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarAutores" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Autores
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarAutores">
                          <li><a class="dropdown-item" href="{{ url_for('author.index') }}">Listado</a></li>
                          <li><a class="dropdown-item" href="{{ url_for('author.add') }}">Agregar</a></li>
                      </ul>
                  </li>
                  <!-- Libros -->
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarLibros" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Libros
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarLibros">
                          <li><a class="dropdown-item" href="{{ url_for('book.index') }}">Listado</a></li>
                          <li><a class="dropdown-item" href="{{ url_for('book.add') }}">Agregar</a></li>
                      </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarComputadoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Computadoras
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarComputadoras">
                        <li><a class="dropdown-item" href="{{ url_for('computers.index') }}">Listado</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('computers.add') }}">Agregar</a></li>
                      </ul>
                  </li>
                  <!-- Préstamos -->
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarPrestamos" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Préstamos de Libros
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarPrestamos">
                          <li><a class="dropdown-item" href="{{ url_for('loan.index') }}">Listado</a></li>
                          <li><a class="dropdown-item" href="{{ url_for('loan.add') }}">Agregar</a></li>
                      </ul>
                  </li>
                    <!-- Préstamos de Computadoras -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarPrestamosComputadoras" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Préstamos de Computadoras
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarPrestamosComputadoras">
                            <li><a class="dropdown-item" href="{{ url_for('cloans.index') }}">Listado</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('cloans.add') }}">Agregar</a></li>
                        </ul>
                    </li>
                 
                                 <!-- Salas -->
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarSalas" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Salas
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarSalas">
                    <li><a class="dropdown-item" href="{{ url_for('room.index') }}">Listado</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('room.add') }}">Agregar</a></li>
                </ul>
            </li>

              </ul>
          </div>
      </div>
    </nav>